name: Latest blog post workflow
on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gautamkrishnar/blog-post-workflow@master
      with:
        feed_list: >-
          https://ac93.uk/articles/index.xml,
          https://wes4m.io/posts/index.xml,
          https://ebulba.dev/feed
        feed_names: >-
          [ally](https://github.com/alistaircol),
          [wes4m](https://github.com/wes4m),
          [bulba](https://github.com/bulb4saur)
        max_post_count: 6
        readme_path: ./profile/README.md
        committer_username: alistaircol
        committer_email: ${{ secrets.COMMITTER_EMAIL }}
        categories_template: >-
          <sup>[`$category`](https://ac93.uk/tags/$category)</sup>&nbsp;
        template: |

          $feedName: [$title]($url)

          > $description

          &nbsp;
